/* ============================================================
   optimize-images.mjs — one-pass image pipeline.
   Re-encodes every raster in public/work to webp (q80, longest
   edge <= MAX_EDGE), removes the heavy original, and writes the
   final on-disk dimensions to src/data/imagedims.js so the
   renderers can emit width/height (kills layout shift / CLS) and
   the home field can frame + lazy-load tiles with known geometry.

   Run:  npm run images
   Originals remain recoverable via git history.
   ============================================================ */
import sharp from 'sharp';
import { readdir, writeFile, unlink, stat } from 'node:fs/promises';
import { join, extname, relative } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname;
const WORK = join(ROOT, 'public/work');
const MAX_EDGE = 1800;
const QUALITY = 80;
const RASTER = new Set(['.jpg', '.jpeg', '.png']);

async function walk(dir) {
  const out = [];
  for (const e of await readdir(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) out.push(...await walk(p));
    else if (RASTER.has(extname(e.name).toLowerCase())) out.push(p);
  }
  return out;
}

const files = await walk(WORK);
const dims = {};
let before = 0, after = 0;

for (const src of files) {
  before += (await stat(src)).size;
  const webpPath = src.replace(/\.(jpe?g|png)$/i, '.webp');
  const img = sharp(src).rotate();                 // respect EXIF orientation
  const meta = await img.metadata();
  const longest = Math.max(meta.width, meta.height);
  const pipe = longest > MAX_EDGE ? img.resize({ width: meta.width >= meta.height ? MAX_EDGE : null, height: meta.height > meta.width ? MAX_EDGE : null }) : img;
  const buf = await pipe.webp({ quality: QUALITY, effort: 5 }).toBuffer({ resolveWithObject: true });
  await writeFile(webpPath, buf.data);
  after += buf.data.length;
  if (src !== webpPath) await unlink(src);          // drop the heavy original (in git history)
  const webUrl = '/' + relative(join(ROOT, 'public'), webpPath);
  dims[webUrl] = [buf.info.width, buf.info.height];
  console.log(`${relative(ROOT, src)}  ->  ${(buf.data.length / 1024).toFixed(0)}KB  ${buf.info.width}x${buf.info.height}`);
}

const sorted = Object.fromEntries(Object.entries(dims).sort());
const body = `/* AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
   Intrinsic on-disk pixel size of each work image, so renderers can emit
   width/height (prevents layout shift) and the field can frame tiles. */
export const IMAGE_DIMS = ${JSON.stringify(sorted, null, 2)};
`;
await writeFile(join(ROOT, 'src/data/imagedims.js'), body);

console.log(`\n${files.length} images: ${(before / 1048576).toFixed(1)}MB -> ${(after / 1048576).toFixed(1)}MB (${(100 - after / before * 100).toFixed(0)}% smaller)`);
console.log('wrote src/data/imagedims.js');
