/* ============================================================
   optimize-images.mjs — one-pass, idempotent image pipeline.
     1. Re-encode any raster in public/work to webp (q80, longest
        edge <= MAX_EDGE) and drop the heavy original.
     2. For every <dir>/cover.webp, generate an <dir>/og.jpg social
        card (1200x630, work centred on white) — JPG renders on
        every scraper, unlike webp.
     3. Write src/data/imagedims.js with each webp's on-disk size so
        renderers can emit width/height (kills CLS) and the field can
        frame + lazy-load tiles with known geometry.

   Run:  npm run images   (safe to re-run; originals stay in git history)
   ============================================================ */
import sharp from 'sharp';
import { readdir, writeFile, unlink, stat } from 'node:fs/promises';
import { join, extname, basename, relative } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname;
const WORK = join(ROOT, 'public/work');
const MAX_EDGE = 1800;
const QUALITY = 80;
const OG = { w: 1200, h: 630, bg: { r: 255, g: 255, b: 255 } };
const RASTER = new Set(['.jpg', '.jpeg', '.png']);

async function walk(dir, pred) {
  const out = [];
  for (const e of await readdir(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) out.push(...await walk(p, pred));
    else if (pred(e.name)) out.push(p);
  }
  return out;
}

/* 1. originals -> webp (no-op on re-runs; og.jpg is never treated as a source) */
const rasters = await walk(WORK, (n) => RASTER.has(extname(n).toLowerCase()) && basename(n) !== 'og.jpg');
let before = 0, after = 0;
for (const src of rasters) {
  before += (await stat(src)).size;
  const webpPath = src.replace(/\.(jpe?g|png)$/i, '.webp');
  const img = sharp(src).rotate();
  const meta = await img.metadata();
  const longest = Math.max(meta.width, meta.height);
  const pipe = longest > MAX_EDGE
    ? img.resize({ width: meta.width >= meta.height ? MAX_EDGE : null, height: meta.height > meta.width ? MAX_EDGE : null })
    : img;
  const buf = await pipe.webp({ quality: QUALITY, effort: 5 }).toBuffer();
  await writeFile(webpPath, buf);
  after += buf.length;
  if (src !== webpPath) await unlink(src);
  console.log(`enc ${relative(ROOT, src)} -> ${(buf.length / 1024).toFixed(0)}KB`);
}
if (rasters.length) console.log(`\n${rasters.length} re-encoded: ${(before / 1048576).toFixed(1)}MB -> ${(after / 1048576).toFixed(1)}MB`);

/* 2. dims map + 3. og cards — always rebuilt from the current webp set */
const webps = await walk(WORK, (n) => extname(n).toLowerCase() === '.webp');
const dims = {};
let cards = 0;
for (const wp of webps) {
  const meta = await sharp(wp).metadata();
  dims['/' + relative(join(ROOT, 'public'), wp)] = [meta.width, meta.height];
  if (basename(wp) === 'cover.webp') {
    const ogPath = join(wp, '..', 'og.jpg');
    await sharp(wp)
      .resize(OG.w, OG.h, { fit: 'contain', background: OG.bg })
      .flatten({ background: OG.bg })
      .jpeg({ quality: 82, mozjpeg: true })
      .toFile(ogPath);
    cards++;
  }
}

const sorted = Object.fromEntries(Object.entries(dims).sort());
await writeFile(join(ROOT, 'src/data/imagedims.js'),
  `/* AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
   Intrinsic on-disk pixel size of each work image, so renderers can emit
   width/height (prevents layout shift) and the field can frame tiles. */
export const IMAGE_DIMS = ${JSON.stringify(sorted, null, 2)};
`);
console.log(`\n${webps.length} webp indexed, ${cards} og cards (1200x630 jpg). wrote src/data/imagedims.js`);
